apiVersion: v1
kind: Service
metadata:
  name: sample-app-ingress-gw # service 이름
  namespace: app # service가 속할 namespace
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: "sample-app-ingress-gw"
    app.kubernetes.io/version: "v1"
    # service의 파드 셀렉터는 엔드포인트 목록을 만드는 데 사용됩니다.
  ports:
    - protocol: TCP
      port: 8088 # 서비스의 포트번호
      targetPort: 8088 # pod의 포트번호