apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-ingress-gw-v1-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: "sample-app-ingress-gw"
      app.kubernetes.io/version: "v1"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "sample-app-ingress-gw"
        app.kubernetes.io/version: "v1"
    spec:
      serviceAccountName: appmesh-virtual-gateway
      containers:
        - name: envoy
          image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.17.2.0-prod
          ports:
            - containerPort: 8088
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi