apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-bar-v1-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-app-bar
      app.kubernetes.io/version: v1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sample-app-bar
        app.kubernetes.io/version: v1
    spec:
      serviceAccountName: appmesh-virtual-node
      containers:
        - image: 242593025403.dkr.ecr.us-west-2.amazonaws.com/sample-app-bar:v1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: sample-app-bar-v1
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 1000m
              memory: 2000Mi
      terminationGracePeriodSeconds: 60
