apiVersion: appmesh.k8s.aws/v1beta2
kind: Mesh
metadata:
  name: sample-appmesh
  namespace: app
spec:
  namespaceSelector:
    matchLabels:
      mesh: sample-appmesh
  egressFilter:
    type: ALLOW_ALL # ALLOW_ALL | DROP_ALL